exclude_paths:
  - tmp
  - vendor

detectors:
  ControlParameter:
    exclude:
      - "Rubysmith::CLI::Actions::Publish#call"
  LongParameterList:
    enabled: false
  TooManyMethods:
    exclude:
      - "Rubysmith::Builder"
  TooManyStatements:
    exclude:
      - "Rubysmith::CLI::Shell#cli"
