inherit_gem:
  caliber: config/all.yml

Metrics/CollectionLiteralLength:
  Exclude:
    - "lib/rubysmith/cli/commands/build.rb"
Metrics/ModuleLength:
  Exclude:
    - "lib/rubysmith/configuration/model.rb"
