inherit_gem:
  caliber: config/all.yml

Metrics/ClassLength:
  Exclude:
    - "lib/rubysmith/builder.rb"
Metrics/CollectionLiteralLength:
  Exclude:
    - "lib/rubysmith/cli/commands/build.rb"
Metrics/ModuleLength:
  Exclude:
    - "lib/rubysmith/configuration/model.rb"
Naming/PredicateMethod:
  AllowedMethods:
    - call
    - install
    - log_error
